
title: 4ren6 Blog 
email: NOEMAIL@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hi there!</h3><h1>Forensic Tech Blogs</h1><h3>日本語で対応しています。!</h3>Hope you like it!"



baseurl: "/DevJournal" # the subpath of your site, e.g. /blog
url: "http://4ren6.github.io" # the base hostname & protocol for your site
twitter_username: TBD
github_username:  TBD

# Build settings
markdown: kramdown
