
# Site settings
title: 4ren6 Ghost
email: johndoe@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>はじめまして４Ren6です!</h3><h1>情報セキュリティブログ始めます。</h1><h3>楽しんでくださいね。</h3>Hope you like it!"



baseurl: "/DevJournal" 
url: "http://4ren6.github.io" 
twitter_username: TBD
github_username:  TBD

# Build settings
markdown: kramdown
